### ISSUE TITLE
ディレクトリ構成が変

### ISSUE THREAD

**Issue by 2bbb** [ryo-simon-mf/vfr_icc_of#1]
折角ならoFのapps/myApps以下にcloneしたら動くような形にしよう

**Comment by ryo-simon-mf** [comment]
手元で動かしたOSと展示マシンのOSが違ってたので一時的なレポジトリです....ご容赦を

**Comment by 2bbb** [comment]
OS違っても構造は一緒で良くない？と思ったけどまあ小言言ってるだけなのでOK！
